apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-api-config
  namespace: chat
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://chat-db.ctkyuwaa0go8.ap-northeast-1.rds.amazonaws.com:5432/chat
  SPRING_DATASOURCE_USERNAME: chat
  SPRING_DATA_REDIS_HOST: chat-redis.j4pb6e.0001.apne1.cache.amazonaws.com
  SPRING_DATA_REDIS_PORT: "6379"
  AWS_REGION: ap-northeast-1
  APP_S3_BUCKET: chat-uploads-831963379503
  APP_SQS_QUEUE_URL: https://sqs.ap-northeast-1.amazonaws.com/831963379503/chat-messages
  COGNITO_ISSUER_URI: https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_qPedGpbby
  COGNITO_USER_POOL_ID: ap-northeast-1_qPedGpbby
  COGNITO_CLIENT_ID: 7vsovq6esg1am78jmk3diucc3q
  APP_SQS_CHAT_MESSAGE_QUEUE: chat-messages
  SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
  SES_FROM_ADDRESS: noreply@tommykeyapp.com
