apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- serviceaccount.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- elasticsearch.yaml
images:
- digest: sha256:1cc6dd91802a8def7b5feb2a00af522ac5e04f7b9e8af3117e072ed7f8c110d8
  name: 831963379503.dkr.ecr.ap-northeast-1.amazonaws.com/chat-api
- digest: sha256:066fa0ae7ec713aea2202ea6fb253f1436c40cf855381b2a7fb26d46dc43bf7f
  name: chat-api
  newName: 831963379503.dkr.ecr.ap-northeast-1.amazonaws.com/chat-api
