apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chat
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:tommykey-apps/chat.git
    targetRevision: main
    path: manifests/base
  destination:
    server: https://kubernetes.default.svc
    namespace: chat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
