apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chat
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: chat-api=831963379503.dkr.ecr.ap-northeast-1.amazonaws.com/chat-api:prod
    argocd-image-updater.argoproj.io/chat-api.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: git@github.com:tommykey-apps/chat.git
    targetRevision: main
    path: manifests/base
  destination:
    server: https://kubernetes.default.svc
    namespace: chat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
