apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argocd-image-updater
    targetRevision: 0.11.0
    helm:
      values: |
        config:
          registries:
            - name: ECR
              api_url: https://831963379503.dkr.ecr.ap-northeast-1.amazonaws.com
              prefix: 831963379503.dkr.ecr.ap-northeast-1.amazonaws.com
              credentials: ext:/scripts/ecr-login.sh
              credsexpire: 10h
        authScripts:
          enabled: true
          scripts:
            ecr-login.sh: |
              #!/bin/sh
              aws ecr get-login-password --region ap-northeast-1
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::831963379503:role/argocd-image-updater
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
